require: 
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'app/channels/**'
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'script/**/*' 
    - 'bin/{rails,rake}'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'config.ru'
    - 'Gemfile'
    - 'Rakefile'

Layout/LineLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 50

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
   
Layout/IndentationWidth:
  Width: 2

Naming/ClassAndModuleCamelCase:
  Enabled: true
 
Naming/MethodName:
  Enabled: true
  EnforcedStyle: snake_case #default

Rails/HasManyOrHasOneDependent:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

